# Generated by Django 3.2 on 2021-04-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='writer',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='body',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='pub_date',
            new_name='upload_date',
        ),
    ]
